name: CPP Build Check

on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: cd scripts && .\GenerateProject.bat && cd ..\build && cmake --build .
